### ISSUE TITLE
Beekeeper reports metrics broken down by table

### ISSUE THREAD

**Issue by max-jacobs** [ExpediaGroup/beekeeper#18]
**Describe the feature**

Beekeeper should create metrics for individual tables.

**Rational**
It would be useful for Beekeeper users to be able to see this broken down by table so they can see only what is relevant to them.

**Comment by massdosage** [comment]
To keep PRs small and focused I'd suggest breaking this up into two issues - one for metrics by table and a second for exceptions (in the latter we can then go through the code and decide on all the errors/warnings that should be counted etc.)

**Comment by max-jacobs** [comment]
Sure thing, will split in to two
